server/src/main/java/server/ServerApplication.java
cors설정 프론트 서버한정 허용
- application bean으로 통합 적용
=> Feat: Add Cors configuration

client/src/App.js, client/src/components/Header.js, client/src/components/QuestionCard.js, client/src/components/SignInModal.js
기본 라우터 구성 해봤습니다.
- 로고 누를시 MianPage로 이동, 
- 카드 누를시 PostPage로 이동.
현재 로그인 버튼을 누를시 로그인 모달로 이동하는 것이 onclick으로 구현되어  있는데 그렇게 할지 아니면 라우팅할지 생각해봐야할 것 같습니다.
그리고 모달 내부에서 라우팅도 고민해봐야할 것 같습니다. 혼자 고민해보다가 일단 기본 라우팅만해서 PR 날립니다!
=> [FE] Feat : 로고 누를시 MianPage로 이동, 카드 누를시 PostPage로 이동.

server/src/main/java/server/user/dto/UserPostDto.java, server/src/main/java/server/user/dto/UserPutDto.java, server/src/main/java/server/user/dto/UserResponseDto.java, server/src/main/java/server/user/entity/User.java, server/src/main/java/server/user/repository/UserRepository.java, server/src/main/java/server/user/service/UserService.java
논의된 바와 같이 `loginId` 사용이 불필요하기 때문에 관련 메서드와 필드 값 제거하였습니다.
- loginId 관련 코드 제거
- 머지 후 브랜치 삭제 부탁드립니다!
#52
=> loginId 제거

server/src/main/java/server/user/dto/UserPostDto.java, server/src/main/java/server/user/dto/UserPutDto.java, server/src/main/java/server/user/dto/UserResponseDto.java, server/src/main/java/server/user/entity/User.java, server/src/main/java/server/user/repository/UserRepository.java, server/src/main/java/server/user/service/UserService.java
회의한 내용대로 닉네임 검증 변경 (한글, 숫자 포함)
- 닉네임 검증 변경
=> nickname validation 변경

server/src/main/java/server/answer/mapper/AnswerMapper.java, server/src/main/java/server/answer/repository/AnswerRepository.java, server/src/main/java/server/answer/service/AnswerService.java, server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/dto/QuestionResponseDto.java, server/src/main/java/server/question/mapper/QuestionMapper.java, server/src/main/java/server/user/dto/UserPostDto.java, server/src/main/java/server/user/dto/UserPutDto.java
QuestionResponseDto에서 AnswerResponseDto에 페이지네이션 적용
- 특정 Question 조회 시 전달되는 Answers에 페이지네이션 적용
merge 후 브랜치 삭제 부탁드립니다.
#57
=> feat: answers 페이지네이션 적용

client/src/components/SignIn.js, client/src/components/SignInModal.js, client/src/components/SignUp.js, client/src/utils/axiosRequest.js
post 기능 구현했습니다. 역시 useForm 이용했습니다.
- post 날리는 부분인데 아직 error 처리부분이나 좀 로직이 미숙합니다.
=> Feat : SignIn axios Post 구현

server/src/main/java/server/answer/controller/AnswerController.java, server/src/main/java/server/answer/entity/Answer.java, server/src/main/java/server/comment/controller/CommentController.java, server/src/main/java/server/jwt/filter/JwtAuthorizationFilter.java, server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/dto/ViewsDto.java, server/src/main/java/server/question/service/QuestionService.java, server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/dto/PasswordDto.java, server/src/main/java/server/user/repository/UserRepository.java, server/src/main/java/server/user/service/UserService.java
기존에 임의적으로 userId로 작성하였던 코드를 로그인 기능이 구현됨에 따라 로그인 유저의 정보를 적용하도록 하였습니다.
Question 조회수 변경 로직 추가하였습니다.
유저 비밀번호 수정 기능 추가하였습니다.
- 각 Controller 메서드에 로그인 사용자 정보 적용 (작성자)
- Question 조회수 변경 기능 추가
- 유저 비밀번호 수정 기능 추가
merge 후 브랜치 삭제 부탁드립니다.
#65 #60 #34
=> Refactor: 컨트롤러 메서드별 로그인 사용자 정보 적용

server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/dto/PasswordDto.java, server/src/main/java/server/user/entity/User.java, server/src/main/java/server/user/service/UserService.java
유저 비밀번호 변경 시 기존 비밀번호 확인하도록 수정
- 암호회된 비밀번호와 비교 검증하는 기능 추가
예외처리는 전체 작업할 때 한번에 하면 좋을 것 같습니다.
임시적으로 메세지가 나가게 코드 작성해두었습니다.
#34
=> fix: 유저 비밀번호 변경 시 기존 비밀번호 확인하도록 수정

server/src/main/java/server/answer/controller/AnswerController.java, server/src/main/java/server/answer/dto/VotesDto.java, server/src/main/java/server/comment/controller/CommentController.java, server/src/main/java/server/comment/dto/CommentPostPutDto.java, server/src/main/java/server/exception/ErrorResponse.java, server/src/main/java/server/exception/GlobalExceptionAdvice.java, server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/dto/ViewsDto.java, server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/dto/UserPostDto.java, server/src/main/java/server/user/dto/UserPutDto.java, server/src/main/java/server/user/service/UserService.java
Dto & URI validation 예외 처리
- Dto & URI validation 예외 처리 진행
- validation 미흡한  부분 보완
이외 에러 추가적으로 처리 필요
#71
=> feat/ validation 예외처리

server/src/main/java/server/answer/repository/AnswerRepository.java, server/src/main/java/server/answer/service/AnswerService.java
조회수와 마찬가지로 업데이트시 갱신시간 업뎃 안되게
- query
리뷰어에게 전달할 내용
관련 이슈 #97
=> fix: Fix updateVotes by query

server/src/main/java/server/jwt/controller/RefreshTokenController.java
PR 내용에 대한 간략한 설명
- /refresh cors 추가
- 분기 return 수정
리뷰어에게 전달할 내용
관련 이슈 #93
=> fix: Set Header Access-Control-Allow-Origin in /refresh

server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/dto/QuestionsResponseDto.java, server/src/main/java/server/question/mapper/QuestionMapper.java
Get Questions 시 반환 값에 answerNum 추가
#105
=> fix: 전체 질문 조회 시 답변 수 추가로 반환하도록 수정

server/src/main/java/server/user/dto/UserProfileResponseDto.java, server/src/main/java/server/user/dto/UserResponseDto.java, server/src/main/java/server/user/mapper/UserMapper.java, server/src/main/java/server/user/service/UserService.java
아래 내용 참고해주세요
- 게시물 조회 시 유저 활동 상태 반환하도록 수정
- 회원가입 시 기본 프로필 이미지 경로 지정되도록 설정
=> refactor: 유저 활동 상태 반환, 기본 프로필 이미지 경로 지정

server/src/main/java/server/answer/controller/AnswerController.java, server/src/main/java/server/question/controller/QuestionController.java
전체질문 조회 Lazy오류 해결 및 오탈자 수정
- Transactional추가
- uri오탈자 수정
=> fix: 전체질문 조회 및 기타

server/src/main/java/server/answer/controller/AnswerController.java, server/src/main/resources/application-test.yml
=> test: Server error test2

server/src/main/java/server/jwt/config/CorsConfig.java
=> cors 문제로 코드 수정

server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/mapper/UserMapper.java
유저페이지에서 로그인 없이 작성글 조회할 수 있도록 수정
- 작성글 조회 api 수정
- 회원 조회 시 status 리턴하도록 수정
=> refactor: 로그인 없이 작성글 조회할 수 있도록 수정

client/src/utils/axiosRequest.js, client/src/utils/useAxiosPrivate.js, server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/mapper/UserMapper.java
유저페이지에서 로그인 없이 작성글 조회할 수 있도록 수정
- 작성글 조회 api 수정
- 회원 조회 시 status 리턴하도록 수정
=> Dev -> test-server

server/scripts/deploy.sh
서버 배포 후 실행이 사용중인 포트 오류로 안되는 부분 수정안입니다.
=> fix: 킬-실행 slepp 10에서 15로 수정

server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
PR 내용에 대한 간략한 설명
- 핵심적으로 변경된 내용1
- 핵심적으로 변경된 내용2
리뷰어에게 전달할 내용
관련 이슈 #1
=> test: 토큰시간 1,10분으로 테스트환경 설정

server/src/main/java/server/jwt/filter/JwtAuthenticationFilter.java
PR 내용에 대한 간략한 설명
- 핵심적으로 변경된 내용1
- 핵심적으로 변경된 내용2
리뷰어에게 전달할 내용
관련 이슈 #1
=> test: 토큰시간 1,10분으로 테스트환경 설정 (#162)

server/build.gradle, server/src/main/resources/application-local.yml, server/src/main/resources/application-main.yml, server/src/main/resources/application-test.yml
sql로그 중복출력 수정 및 추가 설정
- 로그만 출력으로 변경
- 포맷, 색 추가 및 값 trace
출력이 너무 지저분한거 같아서 검토해보니 로그랑 콘솔 중복 출력되고 있었네요.
=> fix: sql로그 중복출력 수정 및 추가 설정

server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/entity/Question.java, server/src/main/java/server/question/repository/QuestionRepository.java, server/src/main/java/server/question/service/QuestionService.java
질문 검색 기능 구현
- 질문 검색이 가능하도록 기능 구현하였습니다.
#143
=> feat: 질문 검색 기능 구현

server/.gitignore, server/src/main/java/server/ServerApplication.java, server/src/main/resources/application-test.yml
주석제거 및 https 추가
- cors 주석 제거
- https 추가
관련 이슈 #123
=> fix: 주석제거 및 https 추가

client/src/components/Pagination.js, client/src/components/QuestionCard.js, client/src/components/QuestionCards.js, client/src/components/Tab/CategoryTabs.js, client/src/components/Tab/Tagbox.js, client/src/pages/MainPage.js, client/src/store/store.js
Category별 Get 기능 구현
- 무한스크롤 삭제했습니다. 무한스크롤 버그가 나는 원인이랑 이런건 나중에 설명드리도록 할게요
- Question Card 에 일단 subCategory가 보이도록 해뒀습니다.
- pagination을 구현해뒀습니다.
관련 이슈 #36
=> [FE] Feat : Category별 Get 기능 구현

client/src/components/Answer.js, client/src/components/AnswerEditModal.js, client/src/components/Pagination.js, client/src/components/QuestionCard.js, client/src/components/QuestionCards.js, client/src/components/Tab/Tagbox.js, client/src/pages/MainPage.js, client/src/pages/UserPage/UserPage.js
- Question Cards에서 가운데 한 칸씩 비는 것 수정했습니다. flex 설정을 잘못했었어서 마지막줄 카드컴포넌트가 2개일경우 그렇게 되더라고요
- TagBox 노동으로 만들던거 배열로 대체하고 원래 태그박스 만드는 부분에서 이벤트버블링 일어나던거 이것저것 실험하다가 e.target을 e.currentTarget으로 바꿔주니까 이벤트버블링이 일어나지 않아서 해결됐습니다.
- myPage에도 Pagination 구현해뒀습니다
- Answer에서 AnswerEditModal로 props.question을 넘기는데 그 props.question이란게 없어서 AnswerEditModal에서 계속 오류가 나는 것 같아서 살짝 수정했습니다. 같은 역할을 하고 있는게 answerStore의 question이라 그걸로 바꿔뒀습니다
=> [FE] Refactor

server/build.gradle, server/src/main/java/server/ServerApplication.java, server/src/main/java/server/crawling/CrawlingScheduler.java, server/src/main/java/server/crawling/entity/Recruit.java, server/src/main/java/server/crawling/repository/RecruitRepository.java
카테고리 관련 구직정보 크롤링 기능 초안입니다.
- 매일 자정에 카테고리 관련 구직정보 갱신
api는 사용 위치 및 용도에 따라 추후 제작하겠습니다.
관련 이슈 #185
=> feat: 카테고리 관련 구직데이터 크롤링 v1

server/src/main/java/server/crawling/CrawlingScheduler.java
데이터 갱신시 이전 데이터 삭제처리
- 다음 갱신시 이전 데이터 모두 삭제 후 갱신
관련 이슈 #185
=> fix: 데이터 갱신시 이전 데이터 삭제처리

client/src/api/post.js, client/src/components/Answer.js, client/src/components/AnswerEditModal.js, client/src/components/AnswerModal.js, client/src/components/UserDropdown.js, client/src/pages/PostPage.js, client/src/store/store.js, client/src/utils/axiosRequest.js
comment post 구현,PostPage 
CRUD시에 화면 렌더링 되도록 구현 ,
마이페이지 접속 에러 해결, 
헤더 마이페이지 접속시 drop-down 닫히도록 구현.
- 페이지네이션 구현
- Comment post 구현
- postpage 리렌더링
관련 이슈 #15
=> Comment Post 구현, 페이지네이션 구현

server/src/main/java/server/answer/controller/AnswerController.java, server/src/main/java/server/answer/service/AnswerService.java, server/src/main/java/server/comment/controller/CommentController.java, server/src/main/java/server/comment/service/CommentService.java, server/src/main/java/server/user/controller/UserController.java, server/src/main/java/server/user/dto/UserResponseDto.java, server/src/main/java/server/user/entity/Badge.java, server/src/main/java/server/user/entity/User.java, server/src/main/java/server/user/mapper/UserMapper.java, server/src/main/java/server/user/repository/BadgeRepository.java, server/src/main/java/server/user/service/UserService.java
답글, 댓글, 좋아요에 관한 점수 추가
- 답글 20, 댓글10, 좋아요 50점
레벨업은 한다면 기준 정하고 구현할 예정입니다.
테이블 추가 완료.
관련 이슈 #202
=> feat: 유저 점수 추가

server/build.gradle, server/src/main/java/server/email/controller/EmailController.java, server/src/main/java/server/email/dto/EmailPostDto.java, server/src/main/java/server/email/dto/EmailResponseDto.java, server/src/main/java/server/email/entity/EmailMessage.java, server/src/main/java/server/email/service/EmailService.java, server/src/main/java/server/user/service/UserService.java, server/src/main/resources/application-main.yml, server/src/main/resources/application-test.yml, server/src/main/resources/templates/email.html, server/src/main/resources/templates/password.html
아래  참고해주세요!
- 회원가입 시 인증 코드를 메일로 발송 (프론트엔드에는 body로 발송)
- 비밀번호 분실 시 임시 비밀번호를 메일로 발송(db 비밀 번호는 발급된 임시 비밀번호로 변경)
혹시 수정해야할 부분이나 잘못된 코드가 있으면 코멘트 부탁드립니다!
#184
=> 이메일 발송 기능 구현

server/src/main/java/server/question/controller/QuestionController.java, server/src/main/java/server/question/service/QuestionService.java
=> feat: 질문 검색 기능에 정렬 추가

client/src/api/Answer/index.js, client/src/api/Answer/post.js, client/src/api/post.js, client/src/components/AnswerModal.js
=> Refactoring 예시

server/src/main/resources/application-local.yml, server/src/main/resources/application-main.yml, server/src/main/resources/application-test.yml, server/src/main/resources/application.yml
모든 환경에서 공통으로 있어야되는 환경을 분류했습니다.
테스트 에러 해결.
- 메일을 공통으로 분류
공통파일로 분류하니까 테스트 에러가 사라졌네요.
=> fix: 공통세팅 분류

client/src/api/Answer/post.js, client/src/api/Comment/post.js, client/src/components/AnswerEditModal.js, client/src/components/AnswerModal.js, client/src/components/Header.js, client/src/components/SignIn.js, client/src/components/SignInModal.js, client/src/components/SignUp.js, client/src/pages/MainPage/QuestionCard.js, client/src/pages/PostPage/Answer.js, client/src/pages/QuestionPostPage.js, client/src/store/store.js
margin 클릭 안되도록 수정
- <Link> 태그가 margin까지 부피를 차지하길래 그냥 onClick 과 useNavigate 사용으로 바꿨습니다.
관련 이슈 #154
=> [FE] Refactor : QuestionCard 사이 마진 클릭 안되도록 수정

client/src/api/Comment/post.js, client/src/components/Header.js, client/src/pages/PostPage/Answer.js, client/src/pages/QuestionPostPage.js, client/src/store/store.js
질문 등록 후 폼 리셋되도록 구현 했습니다.
- 질문 등록 후 폼 리셋.
리뷰어에게 전달할 내용
관련 이슈 #154
=> 질문 등록 후 폼 리셋.

client/src/App.js, client/src/api/User/delete.js, client/src/api/User/index.js, client/src/components/ScrollToTop.js, client/src/components/Tab/CategoryTabs.js, client/src/components/Tab/Tagbox.js, client/src/components/Tab/UserTab.js, client/src/pages/MainPage/MainPage.js, client/src/pages/MainPage/QuestionCard.js, client/src/store/store.js, client/src/utils/timeHandler.js
UI 리팩토링
- scrollToTop 버튼을 하나 만들었습니다.(진혁님이 원래 만들었던 것과 똑같은 파일이 있길래 진혁님꺼는 utils로 보내고 제꺼 scrollToTopButton을 component에 뒀습니다.
- subCategory 이미지 빼달라고 하셔서 이미지 뺐습니다.
- questionCard UI를 살짝 바꿨습니다
관련 이슈 #1
=> [FE] Refactor : UI

server/build.gradle, server/src/main/java/server/crawling/CrawlingScheduler.java, server/src/main/java/server/crawling/controller/RecruitController.java, server/src/main/java/server/crawling/dto/RecruitResponseDto.java, server/src/main/java/server/crawling/mapper/RecruitMapper.java, server/src/main/java/server/crawling/repository/RecruitRepository.java, server/src/main/java/server/crawling/service/RecruitService.java, server/src/main/java/server/user/dto/PasswordDto.java, server/src/main/java/server/user/dto/UserDto.java, server/src/main/java/server/user/dto/UserPostDto.java, server/src/test/java/server/user/controller/UserControllerTest.java
UserControllerTest 작성후 구직데이터 조회 api 추가했습니다.
- 카테고리별 구직 데이터 조회
테스트는 늘상 그렇지만 맞게 작성한건지를 모르겠군요..
관련 이슈 #219 #185
=> UserControllerTest 작성 및 구직 api 추가

server/src/main/java/server/exception/ExceptionCode.java, server/src/main/java/server/jwt/config/SecurityConfig.java, server/src/main/java/server/jwt/handler/CustomAccessDeniedHandler.java, server/src/main/java/server/jwt/handler/CustomHttp403ForbiddenEntryPoint.java
필터에서 던지는 에러응답 처리
- 비로그인시 권한없는 에러응답 추가
- 로그인후 권한없는 에러응답 추가
필터단에서 처리하는 에러를 커스텀 처리로 변경했습니다.
관련 이슈 #247
=> fix: 필터에서 던지는 에러응답 처리

client/src/App.js, client/src/api/Answer/delete.js, client/src/api/Answer/post.js, client/src/api/Answer/votes.js, client/src/api/Comment/post.js, client/src/api/Question/post.js, client/src/api/User/delete.js, client/src/api/User/logout.js, client/src/api/User/signIn.js, client/src/api/User/signUp.js, client/src/components/AnswerModal.js, client/src/components/CommentEditForm.js, client/src/components/SignIn.js, client/src/components/SignUp.js, client/src/pages/MainPage/Carousel/Carousel.js, client/src/pages/MainPage/MainPage.js, client/src/pages/PostPage/Answer.js, client/src/pages/PostPage/QuestionPostPage.js, client/src/store/store.js, client/src/utils/axiosInstance.js, server/src/main/java/server/exception/ExceptionCode.java, server/src/main/java/server/jwt/config/SecurityConfig.java, server/src/main/java/server/jwt/handler/CustomAccessDeniedHandler.java, server/src/main/java/server/jwt/handler/CustomHttp403ForbiddenEntryPoint.java
=> Dev->main merge

client/src/components/SearchForm.js, client/src/components/SignInModal.js, client/src/components/Tab/Tagbox.js, client/src/pages/MainPage/MainPage.js
로그인 모달내부 버튼 스타일 변경하고 메인페이지 select,search 레이아웃 변경했는데 더 보기 좋게 바꾸셔도 좋습니다.
- 모달 내부 버튼 변경
- 레이아웃 변경
관련 이슈 #196
=> [FE] Refactor : 로그인 모달내부 버튼 스타일 변경, 메인페이지 select,search 레이아웃 변경

.github/workflows/front-dev.yml, client/package-lock.json, client/package.json, client/public/index.html, client/src/components/SearchForm.js, client/src/components/SignInModal.js, client/src/components/Tab/CategoryTabs.js, client/src/components/Tab/Tagbox.js, client/src/pages/MainPage/Carousel/Carousel.js, client/src/pages/MainPage/MainPage.js, client/src/pages/PostPage/Answer.js, client/src/pages/UserPage/ModifyUserPage.js, server/src/main/java/server/exception/ExceptionCode.java, server/src/main/java/server/jwt/handler/UserAuthenticationFailureHandler.java, server/src/main/java/server/jwt/oauth/PrincipalDetails.java, server/src/main/java/server/user/controller/UserController.java
=> 보안 문제로 인한 수정 사항 적용

client/package.json, client/src/api/Answer/put.js, client/src/api/Comment/delete.js, client/src/api/Comment/put.js, client/src/api/User/modify.js, client/src/api/User/refresh.js, client/src/components/Header.js, client/src/components/SearchForm.js, client/src/components/UserDropdown.js, client/src/pages/LoginPage/SignIn.js, client/src/pages/LoginPage/SignUp.js, client/src/pages/MainPage/Components/Carousel.js, client/src/pages/MainPage/Components/CategoryTabs.js, client/src/pages/MainPage/Components/QuestionCard.js, client/src/pages/MainPage/Components/Tagbox.js, client/src/pages/PostPage/Answer.js, client/src/pages/PostPage/PostPage.js, client/src/pages/PostPage/QuestionPostPage.js, client/src/pages/UserPage/Components/AnswerComment.js, client/src/pages/UserPage/Components/UserTab.js, client/src/pages/UserPage/UserPage.js, client/src/store/store.js
=> Refactoring : 웹 접근성을 고려한 코드작성

client/package.json, client/src/api/Answer/put.js, client/src/api/Comment/delete.js, client/src/api/Comment/put.js, client/src/api/User/modify.js, client/src/api/User/refresh.js, client/src/components/Header.js, client/src/components/SearchForm.js, client/src/components/UserDropdown.js, client/src/pages/LoginPage/SignIn.js, client/src/pages/LoginPage/SignUp.js, client/src/pages/MainPage/Components/Carousel.js, client/src/pages/MainPage/Components/CategoryTabs.js, client/src/pages/MainPage/Components/QuestionCard.js, client/src/pages/MainPage/Components/QuestionCards.js, client/src/pages/MainPage/Components/Tagbox.js, client/src/pages/MainPage/MainPage.js, client/src/pages/PostPage/Answer.js, client/src/pages/PostPage/PostPage.js, client/src/pages/PostPage/QuestionPostPage.js, client/src/pages/UserPage/Components/AnswerComment.js, client/src/pages/UserPage/Components/ProfileModal.js, client/src/pages/UserPage/Components/UserTab.js, client/src/pages/UserPage/UserInfoPage.js, client/src/pages/UserPage/UserPage.js, client/src/store/store.js
userInfoPage에서 내답변, 내댓글에서 page 수정 제대로 안적용되던거 dependency array 추가해줬음
=> Refactoring : userInfoPage 수정
